name: Generate Snake

on:
  schedule: # Runs at 23:59 every day
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # set to 'svg' to get a svg file as result
          # set to 'gif' to get a gif file as result
          # set to 'png' to get a png file as result
          output: "github-contribution-grid-snake.svg"

      - name: Push Snake Grid to the repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
          directory: "."

